### ISSUE TITLE
Sharing - Micrometer doc improvements

### ISSUE THREAD

**Issue by cpeeyush** [agera-edc/micrometer-docs#2]
Story for feature agera-edc/DataSpaceConnector#49 

### Description

During review of PR (https://github.com/agera-edc/DataSpaceConnector/pull/6) we identified a potential sharing item, Micrometer library docs can be improved further to explain

- Micrometer integration with Jetty.
- Micrometer integration with Jersey

PR [discussion](https://github.com/agera-edc/DataSpaceConnector/pull/6#discussion_r800714099).

### Acceptance Criteria

- [x] Micrometer documentation improved to explain integration with Jetty & Jersey.
- [x] Code samples has been provided if needed.

### Tasks

- [x] Document contribution with code samples.
- [x] Create PR for community contribution and gather feedback.

### Notes
[Dummy PR](https://github.com/agera-edc/micrometer-docs/pull/1) for review

**Comment by algattik** [comment]
Upstream PR https://github.com/micrometer-metrics/micrometer-docs/pull/227
